#!/bin/bash

DIRECTORY="$(dirname "$(dirname "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )")")"

function error {
  echo -e "\\e[91m$1\\e[39m"
  exit 1
}

if dpkg -l steam-devices ;then
  echo "Removing steam-devices package because it conflicts with steam-launcher..."
  sudo apt purge -y steam-devices
fi

echo "Downloading steam.deb"
wget https://steamcdn-a.akamaihd.net/client/installer/steam.deb || error "Failed to download steam.deb!"

sudo apt install ~/steam.deb || error "apt failed to install steam.deb!"

rm ~/steam.deb

exit 0
